apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: gcr.io/hardy-tine-435523-b0/backend
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: db-credentials
        - configMapRef:
            name: gcp-config  # Include this line to reference the ConfigMap
