options:
  logging: CLOUD_LOGGING_ONLY
  env:
    - 'CLOUDSDK_CONTAINER_CLUSTER=k8s-cluster'
    - 'CLOUDSDK_CONTAINER_ZONE=us-central1'
    - 'CLOUDSDK_CORE_PROJECT=braided-upgrade-435523-j8'
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA', './Frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA', './Backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backend:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/backend', 'backend=gcr.io/$PROJECT_ID/backend:$SHORT_SHA', '--namespace=backend']

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['set', 'image', 'deployment/nginx', 'nginx=gcr.io/$PROJECT_ID/nginx:$SHORT_SHA', '--namespace=frontend']


timeout: '1200s'
