apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend  # Update to your desired namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/hardy-tine-435523-b0/frontend
        ports:
        - containerPort: 80
        # You can include additional configurations here if needed.
